# input configs
samples:                                  metadata/samples_pandora_paper_tag1.csv
variant_calls:                            metadata/variant_calls_pandora_paper_tag1.csv
deduplicated_variants_output_folder:      ../pangenome_variations/output_pangenome_variations_pandora_paper_tag1
data_from_paper:                          True


# output configs
output_folder:                            analysis_output_pandora_paper_tag1_with_filters
variant_calls_flank_length_for_precision: 150
max_gt_conf_percentile:                   51
step_gt_conf_percentile:                  5


# filtering configs
coverage_filters:                         [5]
strand_bias_filters:                      [0.05]
gaps_filters:                             [0.8]
